version: '3.8'

services:
  server:
    build: .
    container_name: my-webhook-server
    ports:
      - '3000:3000'
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    volumes:
      - .:/usr/src/app
    # The command to run your server (from Dockerfile or override here)
    command: ['npm', 'run', 'dev'] # or "node dist/server.js"

  worker:
    build: .
    container_name: my-webhook-worker
    # No ports needed, since the worker doesn't expose HTTP
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SERVER_HOST=server
      - SERVER_PORT=3000
    depends_on:
      - redis
    volumes:
      - .:/usr/src/app
    # Use a different command for the worker process
    command: ['npm', 'run', 'worker']

  redis:
    image: 'redis:7-alpine'
    container_name: my-redis
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

volumes:
  redis-data:
